AWSTemplateFormatVersion: "2010-09-09"
Description: DynamoDB Customer Table
Parameters:
  HashKeyElementName:
    Description: HashType PrimaryKey Name
    Type: String
    AllowedPattern: "[a-zA-Z0-9]*"
    MinLength: '1'
    MaxLength: '2048'
    ConstraintDescription: must contain only alphanumberic characters
  HashKeyElementType:
    Description: HashType PrimaryKey Type
    Type: String
    Default: S
    AllowedPattern: "[S|N]"
    MinLength: '1'
    MaxLength: '1'
    ConstraintDescription: must be either S or N
  ReadCapacityUnits:
    Description: Provisioned read throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '5'
    ConstraintDescription: must be 5
  WriteCapacityUnits:
    Description: Provisioned write throughput
    Type: Number
    Default: '5'
    MinValue: '5'
    MaxValue: '5'
    ConstraintDescription: must be 5
Resources:
  MlaaiCustomer:
    Type: AWS::DynamoDB::Table
    Properties:
      AttributeDefinitions: 
      - AttributeName:
          Ref: HashKeyElementName
        AttributeType: "S"
      - AttributeName: "FirstName"
        AttributeType: "S"
      KeySchema:
      - AttributeName:
          Ref: HashKeyElementName
        KeyType: "HASH"
      - AttributeName: "FirstName"
        KeyType: "RANGE"
      PointInTimeRecoverySpecification: 
        PointInTimeRecoveryEnabled: true
      ProvisionedThroughput:
        ReadCapacityUnits:
          Ref: ReadCapacityUnits
        WriteCapacityUnits:
          Ref: WriteCapacityUnits
      StreamSpecification: 
        StreamViewType: "NEW_AND_OLD_IMAGES"
      TableName: "MlaaiCustomer"
      GlobalSecondaryIndexes:
      - IndexName: "IdxGS1"
        KeySchema: 
          - AttributeName:
              Ref: HashKeyElementName
            KeyType: "HASH"
          - AttributeName: "FirstName"
            KeyType: "RANGE"
        Projection: 
          NonKeyAttributes: 
            - "FirstName"
          ProjectionType: "INCLUDE"
        ProvisionedThroughput: 
          ReadCapacityUnits: "5"
          WriteCapacityUnits: "5"
      Tags: 
      - 
        Key: "Project"
        Value: "A"
Outputs:
  TableName:
    Value:
      Ref: MlaaiCustomer
    Description: Mlaai Customer Table